name: Python CI with Pytest and SonarCloud

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      working-directory: ./Gears
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Pytest
      working-directory: ./Gears
      run: |
        export PYTHONPATH=$(pwd) && pytest --cov=Gears --cov-report=lcov tests/

    - name: Upload coverage report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.lcov
        
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v5
      with:
        args: -Dsonar.python.coverage.reportPaths=coverage.lcov
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
