name: Python CI with Pytest and SonarCloud

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      working-directory: ./Gears
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Pytest
      working-directory: ./Gears
      run: |
        pytest tests/  # Adjust path if necessary

    - name: Set up SonarCloud
      uses: sonarsource/sonarcloud-github-action@v1
      with:
        organization: ${{ secrets.SONAR_ORG }}  # Your SonarCloud organization
        token: ${{ secrets.SONAR_TOKEN }}  # Your SonarCloud token

    - name: Run SonarCloud analysis
      working-directory: ./Gears
      run: sonar-scanner
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
